### ISSUE TITLE
Embed https://www.npmjs.com/package/urlsearchparams directly in package

### ISSUE THREAD

**Issue by niftylettuce** [glazedio/frisbee#7]
So we can do stuff like this without needing querystring modules.

```js
 let params = new URLSearchParams();
        params.append('key', 'foobar');
        params.append('language', 'en');
        params.append('location', [
          coords.latitude,
          coords.longitude
        ].join(','));
        params.append('radius', 500);
        googleapi.get(
          '/maps/api/place/nearbysearch/json',
          { body: params },
          (err, res, message) => {
            console.log('googleapi', 'err', err,
                        'res', res, 'message', message);
          }
        );
```

**Comment by joshgillies** [comment]
With the above implemented any idea when this will be implemented?

**Comment by niftylettuce** [comment]
@joshgillies does `v1.0.0` work for you now?  I JSON.stringify the body if its an object or array, this prob not needed anymore

**Comment by joshgillies** [comment]
Nice thought about using `JSON.stringify` on the body as opposed to using the `querystring` module. Will give it a go 👍

**Comment by niftylettuce** [comment]
@joshgillies Actually you gave me a great idea, I will implement EXACTLY what you need.  Give me 10 minutes please.

**Comment by niftylettuce** [comment]
Okay @joshgillies you can try `npm install --save frisbee@1.0.1` from NPM, and you should be able to easily do GET requests with automatic querystring stringification.

For example, you can do this:

```js
// now let's get a list of messages filtered by page and limit
res = await api.get('/v1/messages', {
  body: {
    limit: 10,
    page: 2
  }
});
```

And it will make a `GET /v1/messages?limit=10&page=2` for you.

**Comment by joshgillies** [comment]
Perfect, thanks!👌

**Comment by niftylettuce** [comment]
@joshgillies feel free to join our slack! http://slack.glazed.io/
